feat: support so_reuseaddr
panjf2000/gnet pull request #280
Opened 2021-11-22 15:35 UTC by zhongweikang

## 1. Are you opening this pull request for bug-fixes, optimizations or new feature?
new feature

## 2. Please describe how these code changes achieve your intention.
支持 so_reuseaddr 可以使得 gnet 在重启过程中，不必因为 timewait 原因而导致：bind: address already in use

## 3. Please link to the relevant issues (if any).
ISSUES https://github.com/panjf2000/gnet/issues/266
ISSUES https://github.com/panjf2000/gnet/issues/272
PR https://github.com/panjf2000/gnet/pull/275

## 4. Which documentation changes (if any) need to be made/updated because of this PR?

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] (optional) I am willing to help maintain this change if there are issues with it later.

2021-11-22 15:38 UTC, zhongweikang commented
已重开，这次ok么？

2021-11-23 05:31 UTC, panjf2000 requested changes

2021-11-23 05:31 UTC, panjf2000 commented on gnet_test.go
> +	reuseaddr bool,
testCodecServe 这个测试里不需要加 reuseaddr 的测试，这里 reuseport 是需要测试不同线程模型，reuseaddr 不需要，所以麻烦这部分测试去掉。

2021-11-23 05:55 UTC, zhongweikang commented
Done

2021-11-23 05:59 UTC, panjf2000 approved these changes
lgtm

2021-11-23 06:00 UTC, merged