opt: implement zero-allocated []byte pool for reusing bytes
panjf2000/gnet pull request #292
Opened 2021-12-10 02:05 UTC by fufuok

---
name: Pull request
about: Propose changes to the code
title: 'zero-allocated []byte pool'
labels: 
assignees: 
---

## 1. Are you opening this pull request for bug-fixes, optimizations or new feature?

Optimizations

## 2. Please describe how these code changes achieve your intention.

**old**

```go
go test -bench=. -run=none -benchtime=3s -benchmem -memprofile=old.mem.pprof
goos: linux
goarch: amd64
pkg: github.com/panjf2000/gnet/pkg/pool/byteslice
cpu: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
BenchmarkByteSlice/Run.N-8              51881646                63.92 ns/op           24 B/op          1 allocs/op
BenchmarkByteSlice/Run.Parallel-8       100000000               34.31 ns/op           24 B/op          1 allocs/op
PASS
ok      github.com/panjf2000/gnet/pkg/pool/byteslice    6.875s
```

![old](https://user-images.githubusercontent.com/4979407/145504683-7e95ce77-afa8-46a3-aa95-3d356609690a.png)

------

**new**

```go
go test -bench=. -run=none -benchtime=3s -benchmem -memprofile=new.mem.pprof
goos: linux
goarch: amd64
pkg: github.com/panjf2000/gnet/pkg/pool/byteslice
cpu: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
BenchmarkByteSlice/Run.N-8              144629972               24.83 ns/op            0 B/op          0 allocs/op
BenchmarkByteSlice/Run.Parallel-8       577906443                5.676 ns/op           0 B/op          0 allocs/op
PASS
ok      github.com/panjf2000/gnet/pkg/pool/byteslice    10.049s
```

![new](https://user-images.githubusercontent.com/4979407/145504711-b95d48f5-fae9-4a07-8737-9734ac44d863.png)

------

[byteslice.mem.pprof.21121010.zip](https://github.com/panjf2000/gnet/files/7689590/byteslice.mem.pprof.21121010.zip)

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [ ] (optional) I am willing to help maintain this change if there are issues with it later.

2021-12-10 15:06 UTC, panjf2000 commented
这个 benchmark 我不太理解，Put() 方法是把 *[]byte 指针放回 sync.Pool，为什么还会每次都分配一个新的 reflect.SliceHeader{}？是不是这个测试有问题？

2021-12-10 15:34 UTC, fufuok commented
可以为现在 dev 分支的 byteslice.go  写一个 benchmark 跑一跑看看.

```go
func BenchmarkByteSlice(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		bs := Get(1024)
		Put(bs)
	}
}
```

```shell
go test -bench=. -run=none -benchtime=3s -benchmem -memprofile=mem.pprof
```

2021-12-10 15:55 UTC, fufuok commented
我的理解是要把切片对应底层数组的指针放到池中, 取出来时再用切片来引用, 才能达到复用底层数组的复用目的.
如果要把切片直接放入池, 可以类似这样:

```go
func (p *Pool) Get(size int) []byte {
	// ...
	buf := p.pools[idx].Get().(*[]byte)
	*buf = (*buf)[:size]
	return buf
}

func (p *Pool) Put(buf *[]byte) {
	// ...
	*buf = (*buf)[:cap(*buf)]
	p.pools[idx].Put(buf)
}
```

2021-12-14 14:42 UTC, panjf2000 commented on pkg/pool/byteslice/byteslice.go
> +	p.pools[idx].Put(unsafe.Pointer(&buf[:1][0]))
这里我有点担心，转成 `unsafe.Pointer` 会导致底层数组地址被 GC 回收吧。

2021-12-14 14:56 UTC, panjf2000 commented
> 我的理解是要把切片对应底层数组的指针放到池中, 取出来时再用切片来引用, 才能达到复用底层数组的复用目的. 如果要把切片直接放入池, 可以类似这样:
> 
> ```go
> func (p *Pool) Get(size int) []byte {
> 	// ...
> 	buf := p.pools[idx].Get().(*[]byte)
> 	*buf = (*buf)[:size]
> 	return buf
> }
> 
> func (p *Pool) Put(buf *[]byte) {
> 	// ...
> 	*buf = (*buf)[:cap(*buf)]
> 	p.pools[idx].Put(buf)
> }
> ```
> 
> 使用时需要用:
> 
> ```go
> data := byteslice.Get(1024)
> copy(*data, "123")
> ```

现在的实现就是因为放入 pool，导致 Put 的入参分配在了堆上了，你修改过后就变成了只把底层数组地址放入 pool，所以 Put 函数的入参 buf 就分配在了栈上，因此 benchmark 显示是 0，但是你这种实现看起来有点 tricky，有在线上大规模验证过吗?

2021-12-14 14:57 UTC, panjf2000 requested changes

2021-12-14 14:57 UTC, panjf2000 commented on pkg/pool/byteslice/byteslice.go
> +	p.pools[idx].Put(unsafe.Pointer(&buf[:1][0]))
为什么不能直接 `&buf[0]` ？还要 re-slice 一下？

2021-12-15 00:56 UTC, fufuok commented on pkg/pool/byteslice/byteslice.go
> +	p.pools[idx].Put(unsafe.Pointer(&buf[:1][0]))
有在2个项目上一直使用. 有一定规模, 没特别大规模, 没发现问题.

只是防止在使用过程中如果被做过 `buf = buf[:0]` 这样的操作. Put 时 `&buf[0]` 会越界. gnet 中使用的地方不存在这种情况.

2021-12-16 14:26 UTC, panjf2000 approved these changes
可以暂时合入观察下。

2021-12-24 02:56 UTC, panjf2000 requested changes

2021-12-24 02:56 UTC, panjf2000 commented on pkg/pool/byteslice/byteslice.go
> +	slice := (*reflect.SliceHeader)(unsafe.Pointer(&buf))
ping @fufuok

2021-12-24 09:00 UTC, fufuok commented on pkg/pool/byteslice/byteslice.go
> +	slice := (*reflect.SliceHeader)(unsafe.Pointer(&buf))
好的.

2021-12-24 09:16 UTC, panjf2000 commented
对了，忘了问你有执行 `go vet` 检查这部分代码吗？
@fufuok

2021-12-24 15:35 UTC, fufuok commented
`go vet` 执行过检查了.

2021-12-24 15:46 UTC, merged

2021-12-24 15:46 UTC, panjf2000 commented
Thank~

2023-08-08 08:23 UTC, WineChord commented on pkg/pool/byteslice/byteslice.go
> +	runtime.KeepAlive(ptr)
请教下这里为什么要有一个 `runtime.KeepAlive` @fufuok