Conn level
panjf2000/gnet pull request #460
Opened 2023-05-04 07:11 UTC by jinxing3114

---
name: Pull request
about: Propose changes to the code
title: ''
labels: ''
assignees: ''
---

## 1. Are you opening this pull request for bug-fixes, optimizations or new feature?
优化gc时间，eventloop connections bigmap 以及 业务段需持有大量Conn，两个层面叠加到一起，gc时间更多。
目前粗略测试结果
       eventloop开4个线程，每个el存20W链接
       现有版本：gc周期要100+ms
       优化后版本：gc周期要30+ms

## 2. Please describe how these code changes achieve your intention.

1.增加gfd结构(byte数组)，存储相应位置信息，engine可通过该值找到相应连接，进而不需要业务方持有conn就可以发送消息。
2.eventloop存储conn使用指针map，量大gc时间过长。调整为map[int]gfd，并增加数组切片存储conn，connSlice[256][]*conn。为防止切片扩容时数据复制，采用分块方式，一级为初始化完成，二级则为有需要申请新的空间，不需要则移除空间。
3.conn结构中指针的成员变量，尽可能都去掉指针。
4.可通过Engine直接处理长链接写入、关闭等

## 3. Please link to the relevant issues (if any).

#334 

## 4. Which documentation changes (if any) need to be made/updated because of this PR?

对现有api是兼容，可增加事例，使用方持有gfd即可完成写入、关闭。
目前方案单个eventloop最大可持有连接数2的24次方(16777216)，eventloop数量限制最大为256。可考虑增加option，控制区块大小等。

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [x] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] (optional) I am willing to help maintain this change if there are issues with it later.

2023-05-07 11:26 UTC, panjf2000 commented
> eventloop开4个线程，每个el存20W链接
现有版本：gc周期要100+ms
优化后版本：gc周期要30+ms

这个能提供下具体的测试方法和结果数据吗？有 demo 代码就更好了，谢谢。

2023-05-07 14:18 UTC, jinxing3114 commented
> 更好

主体流程是模拟数据，不依赖客户端。服务启动后制造假数据，然后定时运行gc，记录gc时间。
我的笔记本电脑cpu：2.4 GHz 八核Intel Core i9。
现有版本测试代码：https://github.com/jinxing3114/gnet/blob/dev-gc/eventloop_test.go
优化后版本测试代码：https://github.com/jinxing3114/gnet/blob/conn-level/eventloop_test.go
两个版本运行测试命令：go test -v -test.run TestServeGC

2023-05-07 14:23 UTC, jinxing3114 commented
目前有个不确定的方案，是在于，业务端异步发送数据，可使用gfd结构完成。但是提供的api是在Engine结构下，并非全局。
有想过将api提升到全局，这样业务端也无须区分是哪个Engine来的链接。想探讨下有没有什么更好的建议。

2023-05-09 07:13 UTC, jinxing3114 commented
从新检查和测试的结果有所不同，目前测试的结论，单个el存储链接越多，gc时间差值越大。
我的笔记本电脑测试结果如下，供参考。

单个eventloop存储200000链接，共4个eventloop。
现有版本，平均周期：80+ms，最低49ms，最高160+ms
优化版本，平均周期：38ms，最低26ms，最高60+ms

单个eventloop存储500000链接，共4个eventloop。
现有版本，平均周期：230+ms，最低194ms，最高300+ms
优化版本，平均周期：72ms，最低64ms，最高90+ms

2023-05-11 04:36 UTC, panjf2000 commented
我看 Github actions 还有失败的，等下我准备先 merge #461，那个 PR 主要是实现 gnet 的 Windows 版本（不用在生产环境，只用来调试和测试），你这个 PR 不需要关心 Windows 版本的代码，那个 PR 里的 Linux 和 macOS 方面的代码基本没修改，只有一点小优化，不过因为修改了很多文件名，我估计合入之后会和你这个 PR 有不少冲突，麻烦你解决下，不巧我们两个比较大的 PR 撞一起了，抱歉。

@jinxing3114

2023-05-11 04:41 UTC, jinxing3114 commented
好的，我去合并一下最新的代码，再提交一下

2023-05-11 06:15 UTC, panjf2000 commented
这几天在忙着搞另一个 PR，还没仔细看你的代码，我刚才看了一眼，你这 PR 的核心应该是 `gfd` 这个数据结构，我看现在是用 `gfd` 搞了一个两级的 slice 来存 conn，你能写一下这个东西的设计思路和实现细节吗？我这两天也把代码过一遍。

2023-05-11 07:21 UTC, jinxing3114 commented
现有版本：connections map[int]*conn 存储链接数据
优化版本：connections map[int]gfd，connSlice [][]*conn。存储链接数据
gfd结构设计：
1.gfd结构设计为byte数组，固定长度。
2.gfd结构中存储fd，el下标，connSlice一二级下标，毫秒级不完成时间戳(防止fd重复)。
优化的思路：
1.connections map存储gfd(非指针数据)，降低gc时间。
2.两级存储链接，第一级为数组，固定数据长度，第二级为区块(conn切片)，初始化完成不会占用过多的内存。
第二级是懒申请内存空间，链接释放时如果二级空间没有可用的链接会归还该空间。整个过程不存在扩容迁移数据。
3.检索方式，先在connections中通过fd查找gfd，如果存在，通过gfd可获取一二级下标直接通过connSlice拿到conn。
4.业务端不需要强制持有Conn，可改为存储gfd，降低gc时间(和connections一个方式)。
5.单个el最多支持存储16,777,216个conn，虽然有上限，但是达到上限也很困难。

2023-05-11 07:32 UTC, panjf2000 commented
谢谢，我刚才把代码看了个七七八八，我觉得有些地方可以再优化一下，我这两天再仔细看一下。

2023-05-11 07:51 UTC, jinxing3114 commented
好的，我如果有可优化的方案也会同步更新到分支。
对于Engine提供的新API，我不确定这样是不是最合适的。
目前我正在测试一些可能会出现的极端情况。

2023-05-13 13:55 UTC, panjf2000 commented
你这个 [commit](https://github.com/panjf2000/gnet/pull/460/commits/210196e9f47c64de1fb786a1531dff969f2516a1) 的问题很大，首先会导致 TestServeGC 后面的测试不知道因为什么而阻塞住，我看 eventloop_test.go 里的例子甚至最后都没主动结束 gnet server，不清楚是不是这个原因，而且因为你在测试文件中重写了 loadblancer.register 方法，导致 load_balancer.go 里的 register 方法被 golangci-lint 报错 unused。
你还是先在本地跑通了新增代码之后再 push 上来吧
@jinxing3114

2023-05-13 14:24 UTC, jinxing3114 commented
TestServeGC的会在检测5次，10秒后会结束任务，相关代码在eventloop_test.go 143行。
golangci-lint跑不通是因为升级了版本，之前测试都是1.51.2，现在的版本是1.52.2，检查结果会有稍许不同，我升级下本地的golangci-lint版本从新修正一下。
测试文件中重写了 loadblancer.register，是为了test会竞态检查，多线程操作connections会提示竞态问题，重写之后会由原线程插入假数据。gc的test非功能性测试，我建议把这个test注释掉。

2023-05-13 15:03 UTC, jinxing3114 commented
还有一个错误，是测试GFD假数据或失效数据的test，里面会随机生成假数据来测试系统是否正常运行。
eventloop.go 273行，里面会对异常的GFD打印报错数据，这个位置的预想，本身是有可能会有无效数据存在的，我是觉得直接跳过忽略即可。
正常可能存在的场景
1.队列中close task在write task之前。这样添加到poller task队列是正常，此时链接还未释放。当执行完close task之后，链接释放、GFD失效，再运行write task时，会检测到GFD异常。
2.业务端在链接释放后，未及时清理，调用了异步任务，后续运行task也会检测到GFD异常。
```go
if c == nil || c.gfd != task.GFD {
	if c == nil {
		el.getLogger().Errorf("failed to find conn for task: %+v", task)
	} else {
		el.getLogger().Errorf("invalid connection for task: %+v, expected gfd: %+v, got: %+v", task, task.GFD, c.gfd)
	}
	return
}
```

2023-05-13 20:05 UTC, jinxing3114 commented
修正问题如下：
1.test测试过程中，eventloopinitconn会影响到其他test服务运行，单个测试任务结束后，设置为0。
2.os_unix_test.go 165行，当s.startMcastClient()运行发生错误会导致atomic.AddInt32(&s.active, -1)，进而影响到shutdown返回。修改方式defer atomic.AddInt32(&s.active, -1)。
3.eventloop_unix增加loadConn方法，保持和windows一致。
4.conn_store限制为只为unix系统，windows未使用该数据。

2023-05-14 03:17 UTC, panjf2000 requested changes
poll_data_unix.go 和 queue.go 的改动如果没有什么实质上性能提升的话，这部分代码就给 revert 掉吧，以前的实现更加优雅简洁，现在的改动反而更加繁琐了。

2023-05-14 04:55 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
改动的目的，是为了去掉PollAttachment的callback，此值为指针，GC时间会更长。

2023-05-14 04:57 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
conn结构还有elastic.Buffer，也想改动为去掉指针，成本太高，放弃修改了。

2023-05-14 04:59 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
可以简单的测试下，切换到dev-gc分支。

2023-05-14 05:15 UTC, panjf2000 commented on internal/netpoll/poll_data_unix.go
这里的 GC 对比会提升很多吗？conn 里本来就有不少不可避免的指针存储了，去掉这一个能提升多少？这个地方改完之后的代码我不是很喜欢，变得臃肿了，如果收益不足的话我宁愿牺牲一点性能换代码的简洁性。

2023-05-14 05:17 UTC, jinxing3114 commented on gnet.go
> +// ==================================== Concurrency-safe API's ====================================
改动确实有点繁琐，queue.go里面task任务是设置回调函数，后改为设置回调类型，此项改动的初衷是为了方便业务端不需要持有Conn(业务端发送也需要存储Conn，很可能也是map[userID]Conn的存储方式，也面临同样的gc问题)，通过Engine使用GFD访问异步写任务。之前我对于Engine的提供此API的形式也不是很确定，我近期也在考虑更换API形式。

2023-05-14 06:05 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
刚才本地测试了一下，单个el存储10W链接，多次测试结果，大概2-6ms的提升。
提升有效果，但并非质的改变，如果综合考虑，我也建议按原有的方式实现。我换成原方式实现，稍后我提交一下代码。

2023-05-14 07:25 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
reactor_optimized 里面err等于shutdown后是否和reactor_default里面设置err为nil，如果是的话，我一起修改了。
```go
if err == errors.ErrEngineShutdown {
	el.engine.opts.Logger.Debugf("main reactor is exiting in terms of the demand from user, %v", err)
}
```

2023-05-14 07:41 UTC, jinxing3114 commented on internal/netpoll/poll_data_unix.go
已提交，Task和PollAttachment相关修改已还原。保留一个修改点：conn的pollAttachment不使用引用，这样gc效率提升的同时，对代码逻辑结构影响非常小，性价比高。

2023-05-14 07:41 UTC, panjf2000 commented on internal/netpoll/poll_data_unix.go
> reactor_optimized 里面err等于shutdown后是否和reactor_default里面设置err为nil，如果是的话，我一起修改了。
> 
> ```go
> if err == errors.ErrEngineShutdown {
> 	el.engine.opts.Logger.Debugf("main reactor is exiting in terms of the demand from user, %v", err)
> }
> ```

是的，这里我之前改漏了。

2023-05-14 07:53 UTC, panjf2000 commented on gnet.go
> +// ==================================== Concurrency-safe API's ====================================
我暂时没想到有什么比较好的办法可以保证并发安全地访问 connStore，除了加锁，但是加锁的话相当于就破坏了整个无锁的设计，gnet 内部就不得不全部加锁访问 connStore。

2023-05-14 08:06 UTC, panjf2000 commented on gnet.go
> +// ==================================== Concurrency-safe API's ====================================
可能最后还是得在 Engine 上加那几个 API，还是通过 Trigger 的方式设置一个 func，通过参数判断操作类型，执行相应的 conn 的方法。

2023-05-14 08:19 UTC, jinxing3114 commented on gnet.go
> +// ==================================== Concurrency-safe API's ====================================
我能想到的安全访问，还是异步设置一个task类型，然后去运行。如果直接获取conn并且保证并发安全，我目前也没有比较好的办法。

2023-05-14 16:13 UTC, panjf2000 commented
新引入来替代 map 的数据结构相关的改造应该差不多了，但是这个新的数据结构有一个潜在风险是：如果业务场景海量短连接的话，连接经常断开新建，有可能会造成 `connStore` 形成稀疏矩阵，因为现在对其的内存回收只能是一行里的所有 `*conn` 被完全删除的时候，回收该行，但是因为连接在 `connStore` 中的分布随机性，极端情况下会形成稀疏矩阵从而基本无法回收内存，导致内存浪费。

现在我在考虑通过 build tags 来切换不同的 `connStore` 的实现，默认是 map，适合那种短连接且数量在合理范围内不会特别多的场景，map 内部动态存储和回收，如果是长连接且数量特别大的场景，则可以切换成新的数据结构，缓解这种场景下的 GC 问题，提升性能。

如果不实现模式切换的话，还有一种方式也可以考虑：定期整理 `connStore`，把稀疏矩阵通过移动元素一行行填满，更新所有的 gfd，然后释放掉空置的内存，但是这种方式的话会导致用户保存的 gfd 失效，有一种办法是不对用户暴露 gfd 这种数据结构，让用户永远都通过 fd 来操作，也就是把现在 `Engine` 的那几个 API 都改成 传入 fd 而非 gfd，然后我们内部再通过 `connStore.fd2gfd` 拿到 gfd 定位到目标 `*conn`。

2023-05-14 16:44 UTC, jinxing3114 commented
> 新引入来替代 map 的数据结构相关的改造应该差不多了，但是这个新的数据结构有一个潜在风险是：如果业务场景是海量短连接的话，连接经常断开新建，有可能会造成 `connStore` 形成稀疏矩阵，现在的内存回收是一行里的所有 `*conn` 被清空之后才能回收该行，但是因为连接在 `connStore` 中的分布随机性，极端情况下会形成稀疏矩阵从而基本无法回收内存，导致内存浪费。
> 
> 现在我在考虑通过 build tags 来切换不同的 `connStore` 的实现，默认是 map，适合那种短连接且数量在合理范围内不会特别多的场景，因为 map 内部是动态存储和回收，不会造成内存浪费；如果是长连接且数量特别大的场景，则可以切换成新的数据结构，缓解这种场景下的 GC 问题，提升性能。
> 
> 如果不实现模式切换的话，还有一种方式也可以考虑：定期整理 `connStore`，把稀疏矩阵通过移动元素一行行填满变得紧凑，更新所有的 gfd，然后释放掉空置的内存，但是这种方式的话会导致用户保存的 gfd 失效，有一种办法是不对用户暴露 gfd 这种数据结构，让用户永远都通过 fd 来操作，也就是把现在 `Engine` 的那几个 API 都改成 传入 fd 而非 gfd，然后我们内部再通过 `connStore.fd2gfd` 拿到 gfd 定位到目标 `*conn`。

Engine无法判断fd属于哪个eventloop，所以只通过fd比较困难，还是得传gfd结构才能实现。
build tag我建议别让业务端更多的配置或操作，维护成本也可能增加不少。
现阶段我的想法是，目前gfd结构的所有用途不是特别完整的方案，可只保留核心诉求，降低gc的作用。
1、暂不提供新API，可以等后续更好的方案再提供。
2、不提供gfd结构，只做内部使用，好处是底层优化，不涉及到业务端修改代码，后期再提供也会比较稳妥。
3、在处理task时，可尝试合并稀疏矩阵(达到一定的比例，比如链接数和已申请空间比)，降低内存使用量。
我先尝试写一版合并系数矩阵的逻辑。

2023-05-14 17:39 UTC, panjf2000 commented
> > 新引入来替代 map 的数据结构相关的改造应该差不多了，但是这个新的数据结构有一个潜在风险是：如果业务场景是海量短连接的话，连接经常断开新建，有可能会造成 `connStore` 形成稀疏矩阵，现在的内存回收是一行里的所有 `*conn` 被清空之后才能回收该行，但是因为连接在 `connStore` 中的分布随机性，极端情况下会形成稀疏矩阵从而基本无法回收内存，导致内存浪费。
> > 现在我在考虑通过 build tags 来切换不同的 `connStore` 的实现，默认是 map，适合那种短连接且数量在合理范围内不会特别多的场景，因为 map 内部是动态存储和回收，不会造成内存浪费；如果是长连接且数量特别大的场景，则可以切换成新的数据结构，缓解这种场景下的 GC 问题，提升性能。
> > 如果不实现模式切换的话，还有一种方式也可以考虑：定期整理 `connStore`，把稀疏矩阵通过移动元素一行行填满变得紧凑，更新所有的 gfd，然后释放掉空置的内存，但是这种方式的话会导致用户保存的 gfd 失效，有一种办法是不对用户暴露 gfd 这种数据结构，让用户永远都通过 fd 来操作，也就是把现在 `Engine` 的那几个 API 都改成 传入 fd 而非 gfd，然后我们内部再通过 `connStore.fd2gfd` 拿到 gfd 定位到目标 `*conn`。
> 
> Engine无法判断fd属于哪个eventloop，所以只通过fd比较困难，还是得传gfd结构才能实现。 build tag我建议别让业务端更多的配置或操作，维护成本也可能增加不少。 现阶段我的想法是，目前gfd结构的所有用途不是特别完整的方案，可只保留核心诉求，降低gc的作用。 1、暂不提供新API，可以等后续更好的方案再提供。 2、不提供gfd结构，只做内部使用，好处是底层优化，不涉及到业务端修改代码，后期再提供也会比较稳妥。 3、在处理task时，可尝试合并稀疏矩阵(达到一定的比例，比如链接数和已申请空间比)，降低内存使用量。 我先尝试写一版合并系数矩阵的逻辑。

刚才没看到你的回复。

关于 build tag 的成本我觉得其实是很低的，这个不是问题。

至于说不提供新 API，我觉得有点可惜，因为引入 gfd 和 connStore 的一个优势就是在大量连接的场景中可以极大地缓解 GC 压力，除了内部的 `*conn` 存储，业务侧那边也是，通常来讲业务层一般也是通过 map[fd]*conn 的方式保存所有连接的，这样的话即便内部的 GC 压力缓解了，业务侧那边还是会造成很大的 GC 停顿，如果有新 API 通过 gfd 操作的话，业务层就可以完全不需要自己保存 `*conn` 了，那么两边的 GC 压力就都能得到大幅降低，整体的服务性能可以有较大的提升。不过你说的也有道理，现在这版的 gfd 未必是最优方案，以后可能还可以有更好的实现，现在增加新 API 以后如果要变更 gfd 结构可能会导致较大的兼容性问题，这个我再考虑考虑。

合并稀疏矩阵的代码你可以先写着，就在最新的代码上写吧，build tag 已经加了，就先不要动吧，等合并逻辑写完之后我们再来看。

2023-05-15 01:22 UTC, panjf2000 commented
> > > 新引入来替代 map 的数据结构相关的改造应该差不多了，但是这个新的数据结构有一个潜在风险是：如果业务场景是海量短连接的话，连接经常断开新建，有可能会造成 `connStore` 形成稀疏矩阵，现在的内存回收是一行里的所有 `*conn` 被清空之后才能回收该行，但是因为连接在 `connStore` 中的分布随机性，极端情况下会形成稀疏矩阵从而基本无法回收内存，导致内存浪费。
> > > 现在我在考虑通过 build tags 来切换不同的 `connStore` 的实现，默认是 map，适合那种短连接且数量在合理范围内不会特别多的场景，因为 map 内部是动态存储和回收，不会造成内存浪费；如果是长连接且数量特别大的场景，则可以切换成新的数据结构，缓解这种场景下的 GC 问题，提升性能。
> > > 如果不实现模式切换的话，还有一种方式也可以考虑：定期整理 `connStore`，把稀疏矩阵通过移动元素一行行填满变得紧凑，更新所有的 gfd，然后释放掉空置的内存，但是这种方式的话会导致用户保存的 gfd 失效，有一种办法是不对用户暴露 gfd 这种数据结构，让用户永远都通过 fd 来操作，也就是把现在 `Engine` 的那几个 API 都改成 传入 fd 而非 gfd，然后我们内部再通过 `connStore.fd2gfd` 拿到 gfd 定位到目标 `*conn`。
> > 
> > 
> > Engine无法判断fd属于哪个eventloop，所以只通过fd比较困难，还是得传gfd结构才能实现。 build tag我建议别让业务端更多的配置或操作，维护成本也可能增加不少。 现阶段我的想法是，目前gfd结构的所有用途不是特别完整的方案，可只保留核心诉求，降低gc的作用。 1、暂不提供新API，可以等后续更好的方案再提供。 2、不提供gfd结构，只做内部使用，好处是底层优化，不涉及到业务端修改代码，后期再提供也会比较稳妥。 3、在处理task时，可尝试合并稀疏矩阵(达到一定的比例，比如链接数和已申请空间比)，降低内存使用量。 我先尝试写一版合并系数矩阵的逻辑。
> 
> 刚才没看到你的回复。
> 
> 关于 build tag 的成本我觉得其实是很低的，这个不是问题。
> 
> 至于说不提供新 API，我觉得有点可惜，因为引入 gfd 和 connStore 的一个优势就是在大量连接的场景中可以极大地缓解 GC 压力，除了内部的 `*conn` 存储，业务侧那边也是，通常来讲业务层一般也是通过 map[fd]*conn 的方式保存所有连接的，这样的话即便内部的 GC 压力缓解了，业务侧那边还是会造成很大的 GC 停顿，如果有新 API 通过 gfd 操作的话，业务层就可以完全不需要自己保存 `*conn` 了，那么两边的 GC 压力就都能得到大幅降低，整体的服务性能可以有较大的提升。不过你说的也有道理，现在这版的 gfd 未必是最优方案，以后可能还可以有更好的实现，现在增加新 API 以后如果要变更 gfd 结构可能会导致较大的兼容性问题，这个我再考虑考虑。
> 
> 合并稀疏矩阵的代码你可以先写着，就在最新的代码上写吧，build tag 已经加了，就先不要动吧，等合并逻辑写完之后我们再来看。

我想过了，最后决定：
1. 暂时移除新 API 以及隐藏 gfd，现在暴露出来确实感觉有点过早了，后面一旦有什么变动的话兼容性问题很大，所以为了稳妥起见还是先隐藏；
2. 实现一个整理稀疏矩阵的逻辑在 `connStore.delConn` 方法中，每次删除连接的时候做一下检查，设置一个自定义阀值，超过了就启动；
3. 保留 build tag，这样用户可以通过 build tag 启用新的数据结构，但是因为新特性没有经过大规模的生产环境验证，为了稳妥起见我们还是提供回退机制，一旦运行过程中发现问题，可以让用户快速回退到默认的 map 实现，后面等到新数据结构验证稳定之后可以考虑移除 build tag，对于用户来说是无感知的。

整理稀疏矩阵的代码我先写一版吧，我现在有一些想法，你就暂时先不用搞了，后面我 push 上来再一起看看。
@jinxing3114

2023-05-15 10:46 UTC, panjf2000 approved these changes

2023-05-15 10:59 UTC, jinxing3114 commented
> @jinxing3114 整理稀疏矩阵的逻辑完成了，有空可以一起看看。

有两个需要调整的地方
gfd 的UpdateIndexes需要是指针类型才能操作本数据，已更改。
合并稀疏矩阵里面更改gfd的index，未同步写入fd2gfd，此未改。
我的想法删除一个，移动一个，这样单次成本低，不需要额外的内存，我已提交到delConn方法内，注释内容是相关处理逻辑。可参考下

2023-05-15 11:29 UTC, panjf2000 commented
每次删除都去移动是可以节省内存，但是有点过于频繁了，每次都要去扫描整个矩阵(直到被删除的位置)，这其实相当于默认了场景就是海量短连接，但是实际上未必是这样，我其实希望是能有一定的容错性，然后触到阀值之后再一次性批量进行整理。

2023-05-15 11:29 UTC, panjf2000 commented
那部分代码注释先留着吧

2023-05-16 05:30 UTC, panjf2000 submitted a review, later dismissed

2023-05-16 06:23 UTC, jinxing3114 commented
我从新提交了一下，发现一个bug，conn_matrix里面addConn时没有更新链接数。
增加了gc的benchmark，方便测试
@panjf2000

2023-05-16 09:18 UTC, panjf2000 approved these changes

2023-05-16 09:27 UTC, merged

2023-05-16 09:27 UTC, panjf2000 commented
代码已经合入主干，感谢贡献代码以及这两周的持续支持~
@jinxing3114