feat: add DialContext and EnrollContext for Client
panjf2000/gnet pull request #543
Opened 2024-03-13 09:28 UTC by leslie-fei

Fixes #541

2024-03-14 05:47 UTC, panjf2000 requested changes

2024-03-14 05:47 UTC, panjf2000 commented on client_unix.go
> +func (cli *Client) DialWithContext(network, address string, ctx interface{}) (Conn, error) {
方法名用 `DialContext` 就行了，简洁一点。

加个注释：// DialContext is like Dial but also accepts an empty interface ctx that can be obtained later via Conn.Context.

2024-03-14 05:47 UTC, panjf2000 commented on client_unix.go
> +func (cli *Client) EnrollWithContext(c net.Conn, ctx interface{}) (Conn, error) {
同上。

2024-03-14 05:47 UTC, panjf2000 commented on client_test.go
> +	var rspCh = handler.rspCh
rspCh := handler.rspCh

2024-03-14 06:31 UTC, leslie-fei commented
都改掉提交了

2024-03-15 03:00 UTC, panjf2000 requested changes
`startGnetClient` 函数现在不需要 `ev` 了，直接移除掉吧。

还有其他的代码格式化问题也一起解决掉吧，不然 `golangci-lint` 会报错。

2024-03-18 02:07 UTC, panjf2000 commented on client_test.go
> +	_ = c
不是这么改的。

2024-03-18 02:11 UTC, leslie-fei commented on client_test.go
> +	_ = c
好的, OnOpen(_ Conn) 是这样的格式吧, 我平时就用go fmt可能还不太习惯

2024-03-18 09:40 UTC, leslie-fei commented
之前存在的几个data race问题我也修复了下

2024-03-18 09:46 UTC, panjf2000 commented
你本地测过了没有？

2024-03-18 09:52 UTC, leslie-fei commented
测过了

2024-03-18 11:49 UTC, panjf2000 requested changes

2024-03-18 11:49 UTC, panjf2000 commented on client_test.go
> +func (ev *clientEvents) OnOpen(Conn) ([]byte, Action) {
这整个回调函数应该可以删掉了。

2024-03-18 11:49 UTC, panjf2000 commented on client_test.go
> -			go startGnetClient(s.tester, s.client, s.clientEV, s.network, s.addr, s.multicore, s.async, netConn)
这里我们已经不再需要 `clientEV`了，它在 `testClientServer` 里的字段也可以删掉了。

2024-03-19 02:05 UTC, leslie-fei commented
改过了, 你看看

2024-03-19 07:26 UTC, panjf2000 approved these changes
LGTM

2024-03-19 07:27 UTC, merged